# Generated by Django 5.0.4 on 2024-05-04 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registered_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
